### ISSUE TITLE
No module named create-flask-app

### ISSUE THREAD

**Issue by ogola89** [isakal/create-flask-app#5] opened 2020-11-18 20:22 UTC
Hi there,

I would love to use this, but when I run `python -m create-flask-app my-app` , I get the following error:  `C:\Users\user\anaconda3\python.exe: No module named create-flask-app`

Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

setuptools 49.2.0.post20200714  (Python 3.8)

**Comment by isakal** [comment] 2020-11-26 18:35
Hello,
I am aware of this problem. This problem is caused by improper project structure and incorrectly set up setup.py config file.
I was thinking of solving this issue for good next week, unless you want to have a go at it.

**Comment by isakal** [comment] 2021-01-24 18:43
The fix is merged into master(c78cc0b4accfd692583857fab58637f7eeac32ff), as well as thoroughly tested and published to [pypi](https://pypi.org/project/createflaskapp/).

Closing for now, feel free to ask anything if something is left unclear.

**Closed as completed by isakal** 2021-01-24 18:43 UTC

**Comment by ogola89** [comment] 2021-01-26 23:07
Great it is working now, thanks!
